// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/users/_ctx': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/users/_ctx').default>>>>
    }
    '/api/users/_errors': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/users/_errors').default>>>>
    }
    '/api/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/users/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/users/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/users/[id].patch').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/users/index.post').default>>>>
    }
    '/': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/index.get').default>>>>
    }
  }
}
export {}