import { z } from "zod";

export const schema = z.object({
  _type: z.string(),
  _id: z.string(),
  name: z.string(),
  ownedElements: z.array(
    z.union([
      z.object({
        _type: z.string(),
        _id: z.string(),
        _parent: z.object({ $ref: z.string() }),
        name: z.string(),
        ownedElements: z.array(
          z.object({
            _type: z.string(),
            _id: z.string(),
            _parent: z.object({ $ref: z.string() }),
            name: z.string(),
            defaultDiagram: z.boolean(),
          }),
        ),
      }),
      z.object({
        _type: z.string(),
        _id: z.string(),
        _parent: z.object({ $ref: z.string() }),
        name: z.string(),
        ownedElements: z.array(
          z.union([
            z.object({
              _type: z.string(),
              _id: z.string(),
              _parent: z.object({ $ref: z.string() }),
              name: z.string(),
              columns: z.array(
                z.union([
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    unique: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    primaryKey: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    length: z.string(),
                    nullable: z.boolean(),
                  }),
                ]),
              ),
            }),
            z.object({
              _type: z.string(),
              _id: z.string(),
              _parent: z.object({ $ref: z.string() }),
              name: z.string(),
              columns: z.array(
                z.union([
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    primaryKey: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    nullable: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    length: z.string(),
                    nullable: z.boolean(),
                  }),
                ]),
              ),
            }),
            z.object({
              _type: z.string(),
              _id: z.string(),
              _parent: z.object({ $ref: z.string() }),
              name: z.string(),
              columns: z.array(
                z.union([
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    primaryKey: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    length: z.string(),
                    nullable: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    nullable: z.boolean(),
                  }),
                ]),
              ),
            }),
            z.object({
              _type: z.string(),
              _id: z.string(),
              _parent: z.object({ $ref: z.string() }),
              name: z.string(),
              ownedElements: z.array(
                z.object({
                  _type: z.string(),
                  _id: z.string(),
                  _parent: z.object({ $ref: z.string() }),
                  name: z.string(),
                  end1: z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    reference: z.object({ $ref: z.string() }),
                    cardinality: z.string(),
                  }),
                  end2: z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    reference: z.object({ $ref: z.string() }),
                    cardinality: z.string(),
                  }),
                }),
              ),
              columns: z.array(
                z.union([
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    primaryKey: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    foreignKey: z.boolean(),
                    referenceTo: z.object({ $ref: z.string() }),
                    nullable: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    length: z.string(),
                    nullable: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    nullable: z.boolean(),
                  }),
                ]),
              ),
            }),
            z.object({
              _type: z.string(),
              _id: z.string(),
              _parent: z.object({ $ref: z.string() }),
              name: z.string(),
              columns: z.array(
                z.object({
                  _type: z.string(),
                  _id: z.string(),
                  _parent: z.object({ $ref: z.string() }),
                  name: z.string(),
                  type: z.string(),
                  primaryKey: z.boolean(),
                }),
              ),
            }),
            z.object({
              _type: z.string(),
              _id: z.string(),
              _parent: z.object({ $ref: z.string() }),
              name: z.string(),
              ownedElements: z.array(
                z.object({
                  _type: z.string(),
                  _id: z.string(),
                  _parent: z.object({ $ref: z.string() }),
                  end1: z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    reference: z.object({ $ref: z.string() }),
                  }),
                  end2: z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    reference: z.object({ $ref: z.string() }),
                    cardinality: z.string(),
                  }),
                }),
              ),
              columns: z.array(
                z.union([
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    primaryKey: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    length: z.string(),
                    nullable: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    nullable: z.boolean(),
                  }),
                ]),
              ),
            }),
            z.object({
              _type: z.string(),
              _id: z.string(),
              _parent: z.object({ $ref: z.string() }),
              name: z.string(),
              ownedElements: z.array(
                z.object({
                  _type: z.string(),
                  _id: z.string(),
                  _parent: z.object({ $ref: z.string() }),
                  name: z.string(),
                  end1: z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    reference: z.object({ $ref: z.string() }),
                    cardinality: z.string(),
                  }),
                  end2: z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    reference: z.object({ $ref: z.string() }),
                    cardinality: z.string(),
                  }),
                }),
              ),
              columns: z.array(
                z.union([
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    primaryKey: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    foreignKey: z.boolean(),
                    referenceTo: z.object({ $ref: z.string() }),
                    nullable: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    nullable: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    length: z.string(),
                    nullable: z.boolean(),
                  }),
                ]),
              ),
            }),
            z.object({
              _type: z.string(),
              _id: z.string(),
              _parent: z.object({ $ref: z.string() }),
              name: z.string(),
              ownedElements: z.array(
                z.object({
                  _type: z.string(),
                  _id: z.string(),
                  _parent: z.object({ $ref: z.string() }),
                  name: z.string(),
                  end1: z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    reference: z.object({ $ref: z.string() }),
                    cardinality: z.string(),
                  }),
                  end2: z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    reference: z.object({ $ref: z.string() }),
                    cardinality: z.string(),
                  }),
                }),
              ),
              columns: z.array(
                z.union([
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    primaryKey: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    length: z.string(),
                    nullable: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    nullable: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    foreignKey: z.boolean(),
                    referenceTo: z.object({ $ref: z.string() }),
                    nullable: z.boolean(),
                  }),
                ]),
              ),
            }),
            z.object({
              _type: z.string(),
              _id: z.string(),
              _parent: z.object({ $ref: z.string() }),
              name: z.string(),
              ownedElements: z.array(
                z.object({
                  _type: z.string(),
                  _id: z.string(),
                  _parent: z.object({ $ref: z.string() }),
                  name: z.string(),
                  end1: z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    reference: z.object({ $ref: z.string() }),
                    cardinality: z.string(),
                  }),
                  end2: z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    reference: z.object({ $ref: z.string() }),
                  }),
                }),
              ),
              columns: z.array(
                z.union([
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    primaryKey: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    foreignKey: z.boolean(),
                    referenceTo: z.object({ $ref: z.string() }),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    nullable: z.boolean(),
                  }),
                ]),
              ),
            }),
            z.object({
              _type: z.string(),
              _id: z.string(),
              _parent: z.object({ $ref: z.string() }),
              name: z.string(),
              columns: z.array(
                z.union([
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    primaryKey: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    length: z.string(),
                    unique: z.boolean(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    length: z.string(),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    name: z.string(),
                    type: z.string(),
                    nullable: z.boolean(),
                  }),
                ]),
              ),
            }),
            z.object({
              _type: z.string(),
              _id: z.string(),
              _parent: z.object({ $ref: z.string() }),
              name: z.string(),
              ownedViews: z.array(
                z.union([
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    model: z.object({ $ref: z.string() }),
                    subViews: z.array(
                      z.union([
                        z.object({
                          _type: z.string(),
                          _id: z.string(),
                          _parent: z.object({ $ref: z.string() }),
                          font: z.string(),
                          parentStyle: z.boolean(),
                          left: z.number(),
                          top: z.number(),
                          width: z.number(),
                          height: z.number(),
                          text: z.string(),
                        }),
                        z.object({
                          _type: z.string(),
                          _id: z.string(),
                          _parent: z.object({ $ref: z.string() }),
                          model: z.object({ $ref: z.string() }),
                          subViews: z.array(
                            z.object({
                              _type: z.string(),
                              _id: z.string(),
                              _parent: z.object({ $ref: z.string() }),
                              model: z.object({ $ref: z.string() }),
                              font: z.string(),
                              parentStyle: z.boolean(),
                              left: z.number(),
                              top: z.number(),
                              width: z.number(),
                              height: z.number(),
                            }),
                          ),
                          font: z.string(),
                          parentStyle: z.boolean(),
                          left: z.number(),
                          top: z.number(),
                          width: z.number(),
                          height: z.number(),
                        }),
                      ]),
                    ),
                    font: z.string(),
                    parentStyle: z.boolean(),
                    left: z.number(),
                    top: z.number(),
                    width: z.number(),
                    height: z.number(),
                    nameLabel: z.object({ $ref: z.string() }),
                    columnCompartment: z.object({ $ref: z.string() }),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    model: z.object({ $ref: z.string() }),
                    subViews: z.array(
                      z.union([
                        z.object({
                          _type: z.string(),
                          _id: z.string(),
                          _parent: z.object({ $ref: z.string() }),
                          font: z.string(),
                          parentStyle: z.boolean(),
                          left: z.number(),
                          top: z.number(),
                          width: z.number(),
                          height: z.number(),
                          alpha: z.number(),
                          distance: z.number(),
                          hostEdge: z.object({ $ref: z.string() }),
                          edgePosition: z.number(),
                          text: z.string(),
                        }),
                        z.object({
                          _type: z.string(),
                          _id: z.string(),
                          _parent: z.object({ $ref: z.string() }),
                          font: z.string(),
                          parentStyle: z.boolean(),
                          left: z.number(),
                          top: z.number(),
                          height: z.number(),
                          alpha: z.number(),
                          distance: z.number(),
                          hostEdge: z.object({ $ref: z.string() }),
                          edgePosition: z.number(),
                        }),
                        z.object({
                          _type: z.string(),
                          _id: z.string(),
                          _parent: z.object({ $ref: z.string() }),
                          font: z.string(),
                          parentStyle: z.boolean(),
                          left: z.number(),
                          top: z.number(),
                          width: z.number(),
                          height: z.number(),
                          alpha: z.number(),
                          distance: z.number(),
                          hostEdge: z.object({ $ref: z.string() }),
                          text: z.string(),
                        }),
                      ]),
                    ),
                    font: z.string(),
                    parentStyle: z.boolean(),
                    head: z.object({ $ref: z.string() }),
                    tail: z.object({ $ref: z.string() }),
                    lineStyle: z.number(),
                    points: z.string(),
                    nameLabel: z.object({ $ref: z.string() }),
                    tailNameLabel: z.object({ $ref: z.string() }),
                    headNameLabel: z.object({ $ref: z.string() }),
                  }),
                  z.object({
                    _type: z.string(),
                    _id: z.string(),
                    _parent: z.object({ $ref: z.string() }),
                    model: z.object({ $ref: z.string() }),
                    subViews: z.array(
                      z.union([
                        z.object({
                          _type: z.string(),
                          _id: z.string(),
                          _parent: z.object({ $ref: z.string() }),
                          visible: z.boolean(),
                          font: z.string(),
                          parentStyle: z.boolean(),
                          left: z.number(),
                          top: z.number(),
                          height: z.number(),
                          alpha: z.number(),
                          distance: z.number(),
                          hostEdge: z.object({ $ref: z.string() }),
                          edgePosition: z.number(),
                        }),
                        z.object({
                          _type: z.string(),
                          _id: z.string(),
                          _parent: z.object({ $ref: z.string() }),
                          font: z.string(),
                          parentStyle: z.boolean(),
                          left: z.number(),
                          top: z.number(),
                          height: z.number(),
                          alpha: z.number(),
                          distance: z.number(),
                          hostEdge: z.object({ $ref: z.string() }),
                          edgePosition: z.number(),
                        }),
                        z.object({
                          _type: z.string(),
                          _id: z.string(),
                          _parent: z.object({ $ref: z.string() }),
                          font: z.string(),
                          parentStyle: z.boolean(),
                          left: z.number(),
                          top: z.number(),
                          height: z.number(),
                          alpha: z.number(),
                          distance: z.number(),
                          hostEdge: z.object({ $ref: z.string() }),
                        }),
                      ]),
                    ),
                    font: z.string(),
                    parentStyle: z.boolean(),
                    head: z.object({ $ref: z.string() }),
                    tail: z.object({ $ref: z.string() }),
                    lineStyle: z.number(),
                    points: z.string(),
                    nameLabel: z.object({ $ref: z.string() }),
                    tailNameLabel: z.object({ $ref: z.string() }),
                    headNameLabel: z.object({ $ref: z.string() }),
                  }),
                ]),
              ),
            }),
          ]),
        ),
      }),
    ]),
  ),
});
